<?xml version="1.0" encoding="utf-8"?><Database Name="DACN" Class="DatabaseClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=VOIANGA\SQLEXPRESS;Initial Catalog=DACN;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DACNConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BANGGIADAT" Member="BANGGIADATs">
    <Type Name="BANGGIADAT">
      <Column Name="ID_BANGGIADAT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_QUANHUYEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDUONG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DOANTU" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="VT1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VT2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VT3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VT4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VT5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_LOAIHINH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_CHITIETLOAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CHITIETLOAI_BANGGIADAT" Member="CHITIETLOAI" ThisKey="ID_CHITIETLOAI" OtherKey="ID_CHITIETLOAI" Type="CHITIETLOAI" IsForeignKey="true" />
      <Association Name="LOAIHINH_BANGGIADAT" Member="LOAIHINH" ThisKey="ID_LOAIHINH" OtherKey="ID_LOAIHINH" Type="LOAIHINH" IsForeignKey="true" />
      <Association Name="QUANHUYEN_BANGGIADAT" Member="QUANHUYEN" ThisKey="ID_QUANHUYEN" OtherKey="ID_QUANHUYEN" Type="QUANHUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VANPHONGCHOTHUE" Member="VANPHONGCHOTHUEs">
    <Type Name="VANPHONGCHOTHUE">
      <Column Name="ID_VPCT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_CHITIETLOAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_LOAIHINH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_CHUNGTHU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOHIEU" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DIENTICHTHUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOIHANTHUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIEUKIENKHAC" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MUCGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOIDIEMGIAODICH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOILAPPHIEU" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGUOIKIEMDUYET" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_LTT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="CHITIETLOAI_VANPHONGCHOTHUE" Member="CHITIETLOAI" ThisKey="ID_CHITIETLOAI" OtherKey="ID_CHITIETLOAI" Type="CHITIETLOAI" IsForeignKey="true" />
      <Association Name="CHUNGTHUTDG_VANPHONGCHOTHUE" Member="CHUNGTHUTDG" ThisKey="ID_CHUNGTHU" OtherKey="ID_CHUNGTHU" Type="CHUNGTHUTDG" IsForeignKey="true" />
      <Association Name="LOAIHINH_VANPHONGCHOTHUE" Member="LOAIHINH" ThisKey="ID_LOAIHINH" OtherKey="ID_LOAIHINH" Type="LOAIHINH" IsForeignKey="true" />
      <Association Name="LOAITHONGTIN_VANPHONGCHOTHUE" Member="LOAITHONGTIN" ThisKey="ID_LTT" OtherKey="ID_LTT" Type="LOAITHONGTIN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CANHOCHUNGCU" Member="CANHOCHUNGCUs">
    <Type Name="CANHOCHUNGCU">
      <Column Name="ID_CHCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_QUANHUYEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_CHUNGTHU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_LOAIHINH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_DDPL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_LTT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TINHCHATCANHO" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DIENTICHCANHO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOPHONGNGU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOPHONGWC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOITHAT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SOTANGCAO" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SOHIEU" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="THANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOIDIEMGIAODICH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOILAPPHIEU" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGUOIKIEMDUYET" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_CHITIETLOAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QUYHOACH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CQMT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="THTT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TTGD" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DKTT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PHANLUONG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CSHT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="THUADAT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TOBANDO" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ID_CAPDUONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_KETCAUDUONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_CRMD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CANHOCHUNGCU_TIENICHCHCC" Member="TIENICHCHCCs" ThisKey="ID_CHCC" OtherKey="ID_CHCC" Type="TIENICHCHCC" />
      <Association Name="CAPDUONG_CANHOCHUNGCU" Member="CAPDUONG" ThisKey="ID_CAPDUONG" OtherKey="ID_CAPDUONG" Type="CAPDUONG" IsForeignKey="true" />
      <Association Name="CHIEURONGMATDUONG_CANHOCHUNGCU" Member="CHIEURONGMATDUONG" ThisKey="ID_CRMD" OtherKey="ID_CRMD" Type="CHIEURONGMATDUONG" IsForeignKey="true" />
      <Association Name="CHITIETLOAI_CANHOCHUNGCU" Member="CHITIETLOAI" ThisKey="ID_CHITIETLOAI" OtherKey="ID_CHITIETLOAI" Type="CHITIETLOAI" IsForeignKey="true" />
      <Association Name="CHUNGTHUTDG_CANHOCHUNGCU" Member="CHUNGTHUTDG" ThisKey="ID_CHUNGTHU" OtherKey="ID_CHUNGTHU" Type="CHUNGTHUTDG" IsForeignKey="true" />
      <Association Name="DACDIEMPHAPLY_CANHOCHUNGCU" Member="DACDIEMPHAPLY" ThisKey="ID_DDPL" OtherKey="ID_DDPL" Type="DACDIEMPHAPLY" IsForeignKey="true" />
      <Association Name="KETCAUDUONG_CANHOCHUNGCU" Member="KETCAUDUONG" ThisKey="ID_KETCAUDUONG" OtherKey="ID_KETCAUDUONG" Type="KETCAUDUONG" IsForeignKey="true" />
      <Association Name="LOAIHINH_CANHOCHUNGCU" Member="LOAIHINH" ThisKey="ID_LOAIHINH" OtherKey="ID_LOAIHINH" Type="LOAIHINH" IsForeignKey="true" />
      <Association Name="LOAITHONGTIN_CANHOCHUNGCU" Member="LOAITHONGTIN" ThisKey="ID_LTT" OtherKey="ID_LTT" Type="LOAITHONGTIN" IsForeignKey="true" />
      <Association Name="QUANHUYEN_CANHOCHUNGCU" Member="QUANHUYEN" ThisKey="ID_QUANHUYEN" OtherKey="ID_QUANHUYEN" Type="QUANHUYEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CAPDUONG" Member="CAPDUONGs">
    <Type Name="CAPDUONG">
      <Column Name="ID_CAPDUONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CAPDUONG_CANHOCHUNGCU" Member="CANHOCHUNGCUs" ThisKey="ID_CAPDUONG" OtherKey="ID_CAPDUONG" Type="CANHOCHUNGCU" />
      <Association Name="CAPDUONG_DAT" Member="DATs" ThisKey="ID_CAPDUONG" OtherKey="ID_CAPDUONG" Type="DAT" />
    </Type>
  </Table>
  <Table Name="dbo.CHIEURONGMATDUONG" Member="CHIEURONGMATDUONGs">
    <Type Name="CHIEURONGMATDUONG">
      <Column Name="ID_CRMD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CHIEURONGMATDUONG_CANHOCHUNGCU" Member="CANHOCHUNGCUs" ThisKey="ID_CRMD" OtherKey="ID_CRMD" Type="CANHOCHUNGCU" />
      <Association Name="CHIEURONGMATDUONG_DAT" Member="DATs" ThisKey="ID_CRMD" OtherKey="ID_CRMD" Type="DAT" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETLOAI" Member="CHITIETLOAIs">
    <Type Name="CHITIETLOAI">
      <Column Name="ID_CHITIETLOAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_LOAITAISAN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CHITIETLOAI_BANGGIADAT" Member="BANGGIADATs" ThisKey="ID_CHITIETLOAI" OtherKey="ID_CHITIETLOAI" Type="BANGGIADAT" />
      <Association Name="CHITIETLOAI_VANPHONGCHOTHUE" Member="VANPHONGCHOTHUEs" ThisKey="ID_CHITIETLOAI" OtherKey="ID_CHITIETLOAI" Type="VANPHONGCHOTHUE" />
      <Association Name="CHITIETLOAI_CANHOCHUNGCU" Member="CANHOCHUNGCUs" ThisKey="ID_CHITIETLOAI" OtherKey="ID_CHITIETLOAI" Type="CANHOCHUNGCU" />
      <Association Name="CHITIETLOAI_CONGTRINHXAYDUNG" Member="CONGTRINHXAYDUNGs" ThisKey="ID_CHITIETLOAI" OtherKey="ID_CHITIETLOAI" Type="CONGTRINHXAYDUNG" />
      <Association Name="CHITIETLOAI_DAT" Member="DATs" ThisKey="ID_CHITIETLOAI" OtherKey="ID_CHITIETLOAI" Type="DAT" />
      <Association Name="LOAITAISAN_CHITIETLOAI" Member="LOAITAISAN" ThisKey="ID_LOAITAISAN" OtherKey="ID_LOAITAISAN" Type="LOAITAISAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUNGTHUTDG" Member="CHUNGTHUTDGs">
    <Type Name="CHUNGTHUTDG">
      <Column Name="ID_CHUNGTHU" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PYC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_HOPDONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOCHUNGTHU" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="NGAYXUAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THOIDIEMTDG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MUCDICHTDG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CACHTIEPCANTDG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PPTDG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="KETQUATDG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CHUNGTHUTDG_VANPHONGCHOTHUE" Member="VANPHONGCHOTHUEs" ThisKey="ID_CHUNGTHU" OtherKey="ID_CHUNGTHU" Type="VANPHONGCHOTHUE" />
      <Association Name="CHUNGTHUTDG_CANHOCHUNGCU" Member="CANHOCHUNGCUs" ThisKey="ID_CHUNGTHU" OtherKey="ID_CHUNGTHU" Type="CANHOCHUNGCU" />
      <Association Name="CHUNGTHUTDG_CONGTRINHXAYDUNG" Member="CONGTRINHXAYDUNGs" ThisKey="ID_CHUNGTHU" OtherKey="ID_CHUNGTHU" Type="CONGTRINHXAYDUNG" />
      <Association Name="CHUNGTHUTDG_DAT" Member="DATs" ThisKey="ID_CHUNGTHU" OtherKey="ID_CHUNGTHU" Type="DAT" />
      <Association Name="CHUNGTHUTDG_FILEDINHKEM" Member="FILEDINHKEMs" ThisKey="ID_CHUNGTHU" OtherKey="ID_CHUNGTHU" Type="FILEDINHKEM" />
      <Association Name="HOPDONG_CHUNGTHUTDG" Member="HOPDONG" ThisKey="ID_HOPDONG" OtherKey="ID_HOPDONG" Type="HOPDONG" IsForeignKey="true" />
      <Association Name="PHIEUYEUCAU_CHUNGTHUTDG" Member="PHIEUYEUCAU" ThisKey="ID_PYC" OtherKey="ID_PYC" Type="PHIEUYEUCAU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONGTRINHXAYDUNG" Member="CONGTRINHXAYDUNGs">
    <Type Name="CONGTRINHXAYDUNG">
      <Column Name="ID_CTXD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_CHITIETLOAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_CHUNGTHU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_LOAIHINH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_DDPL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOHIEU" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DIENTICHLODAT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TANGHAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TANGNOI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MATDOXAYDUNG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIENTICHXAYDUNG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAMXAYDUNG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CHATLUONGCONLAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MUCDOHOANTHANH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIATRICONLAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOIDIEMGIAODICH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOILAPPHIEU" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGUOIKIEMDUYET" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_LTT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MONG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TUONGVACH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="KETCAUCHIULUC" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="[TRAN]" Member="TRAN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MAI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NOITHAT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="CHUNGTHUTDG_CONGTRINHXAYDUNG" Member="CHUNGTHUTDG" ThisKey="ID_CHUNGTHU" OtherKey="ID_CHUNGTHU" Type="CHUNGTHUTDG" IsForeignKey="true" />
      <Association Name="CHITIETLOAI_CONGTRINHXAYDUNG" Member="CHITIETLOAI" ThisKey="ID_CHITIETLOAI" OtherKey="ID_CHITIETLOAI" Type="CHITIETLOAI" IsForeignKey="true" />
      <Association Name="DACDIEMPHAPLY_CONGTRINHXAYDUNG" Member="DACDIEMPHAPLY" ThisKey="ID_DDPL" OtherKey="ID_DDPL" Type="DACDIEMPHAPLY" IsForeignKey="true" />
      <Association Name="LOAIHINH_CONGTRINHXAYDUNG" Member="LOAIHINH" ThisKey="ID_LOAIHINH" OtherKey="ID_LOAIHINH" Type="LOAIHINH" IsForeignKey="true" />
      <Association Name="LOAITHONGTIN_CONGTRINHXAYDUNG" Member="LOAITHONGTIN" ThisKey="ID_LTT" OtherKey="ID_LTT" Type="LOAITHONGTIN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DACDIEMPHAPLY" Member="DACDIEMPHAPLies">
    <Type Name="DACDIEMPHAPLY">
      <Column Name="ID_DDPL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_LOAITAISAN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DACDIEMPHAPLY_CANHOCHUNGCU" Member="CANHOCHUNGCUs" ThisKey="ID_DDPL" OtherKey="ID_DDPL" Type="CANHOCHUNGCU" />
      <Association Name="DACDIEMPHAPLY_CONGTRINHXAYDUNG" Member="CONGTRINHXAYDUNGs" ThisKey="ID_DDPL" OtherKey="ID_DDPL" Type="CONGTRINHXAYDUNG" />
      <Association Name="DACDIEMPHAPLY_DAT" Member="DATs" ThisKey="ID_DDPL" OtherKey="ID_DDPL" Type="DAT" />
      <Association Name="LOAITAISAN_DACDIEMPHAPLY" Member="LOAITAISAN" ThisKey="ID_LOAITAISAN" OtherKey="ID_LOAITAISAN" Type="LOAITAISAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DAT" Member="DATs">
    <Type Name="DAT">
      <Column Name="ID_DAT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DDPL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_LOAIHINH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_CHUNGTHU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOHIEU" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DIENTICHLODAT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TANGHAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TANGNOI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MATDOXAYDUNG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIENTICHXAYDUNG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAMXAYDUNG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CHATLUONGCONLAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MUCDOHOANTHANH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIATRICONLAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THOIDIEMGIAODICH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOILAPPHIEU" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGUOIKIEMDUYET" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_LTT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MDSD" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CTHH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="HINHDANG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="THSD" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGSD" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="QUYHOACH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CQMT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DKTT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TTGD" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="THTT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PHANLUONG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CSHT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="THUADAT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TOBANDO" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ID_CHITIETLOAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_CAPDUONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_KETCAUDUONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_CRMD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CAPDUONG_DAT" Member="CAPDUONG" ThisKey="ID_CAPDUONG" OtherKey="ID_CAPDUONG" Type="CAPDUONG" IsForeignKey="true" />
      <Association Name="CHITIETLOAI_DAT" Member="CHITIETLOAI" ThisKey="ID_CHITIETLOAI" OtherKey="ID_CHITIETLOAI" Type="CHITIETLOAI" IsForeignKey="true" />
      <Association Name="CHUNGTHUTDG_DAT" Member="CHUNGTHUTDG" ThisKey="ID_CHUNGTHU" OtherKey="ID_CHUNGTHU" Type="CHUNGTHUTDG" IsForeignKey="true" />
      <Association Name="CHIEURONGMATDUONG_DAT" Member="CHIEURONGMATDUONG" ThisKey="ID_CRMD" OtherKey="ID_CRMD" Type="CHIEURONGMATDUONG" IsForeignKey="true" />
      <Association Name="DACDIEMPHAPLY_DAT" Member="DACDIEMPHAPLY" ThisKey="ID_DDPL" OtherKey="ID_DDPL" Type="DACDIEMPHAPLY" IsForeignKey="true" />
      <Association Name="KETCAUDUONG_DAT" Member="KETCAUDUONG" ThisKey="ID_KETCAUDUONG" OtherKey="ID_KETCAUDUONG" Type="KETCAUDUONG" IsForeignKey="true" />
      <Association Name="LOAIHINH_DAT" Member="LOAIHINH" ThisKey="ID_LOAIHINH" OtherKey="ID_LOAIHINH" Type="LOAIHINH" IsForeignKey="true" />
      <Association Name="LOAITHONGTIN_DAT" Member="LOAITHONGTIN" ThisKey="ID_LTT" OtherKey="ID_LTT" Type="LOAITHONGTIN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FILEDINHKEM" Member="FILEDINHKEMs">
    <Type Name="FILEDINHKEM">
      <Column Name="ID_FILEDINHKEM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENFILE" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LIENKET" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_PYC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_HOPDONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_CHUNGTHU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CHUNGTHUTDG_FILEDINHKEM" Member="CHUNGTHUTDG" ThisKey="ID_CHUNGTHU" OtherKey="ID_CHUNGTHU" Type="CHUNGTHUTDG" IsForeignKey="true" />
      <Association Name="HOPDONG_FILEDINHKEM" Member="HOPDONG" ThisKey="ID_HOPDONG" OtherKey="ID_HOPDONG" Type="HOPDONG" IsForeignKey="true" />
      <Association Name="PHIEUYEUCAU_FILEDINHKEM" Member="PHIEUYEUCAU" ThisKey="ID_PYC" OtherKey="ID_PYC" Type="PHIEUYEUCAU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOPDONG" Member="HOPDONGs">
    <Type Name="HOPDONG">
      <Column Name="ID_HOPDONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SOHD" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ID_NHANVIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIAKE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOAHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CHIETKHAU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATHANHTOAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOANHTHUTHUC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TRANGTHAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_PYC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_LOAIHOPDONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOPDONG_CHUNGTHUTDG" Member="CHUNGTHUTDGs" ThisKey="ID_HOPDONG" OtherKey="ID_HOPDONG" Type="CHUNGTHUTDG" />
      <Association Name="HOPDONG_FILEDINHKEM" Member="FILEDINHKEMs" ThisKey="ID_HOPDONG" OtherKey="ID_HOPDONG" Type="FILEDINHKEM" />
      <Association Name="LOAIHOPDONG_HOPDONG" Member="LOAIHOPDONG" ThisKey="ID_LOAIHOPDONG" OtherKey="ID_LOAIHOPDONG" Type="LOAIHOPDONG" IsForeignKey="true" />
      <Association Name="NHANVIEN_HOPDONG" Member="NHANVIEN" ThisKey="ID_NHANVIEN" OtherKey="ID_NHANVIEN" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="PHIEUYEUCAU_HOPDONG" Member="PHIEUYEUCAU" ThisKey="ID_PYC" OtherKey="ID_PYC" Type="PHIEUYEUCAU" IsForeignKey="true" />
      <Association Name="TRANGTHAI_HOPDONG" Member="TRANGTHAI1" ThisKey="ID_TRANGTHAI" OtherKey="ID_TRANGTHAI" Type="TRANGTHAI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KETCAUDUONG" Member="KETCAUDUONGs">
    <Type Name="KETCAUDUONG">
      <Column Name="ID_KETCAUDUONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KETCAUDUONG_CANHOCHUNGCU" Member="CANHOCHUNGCUs" ThisKey="ID_KETCAUDUONG" OtherKey="ID_KETCAUDUONG" Type="CANHOCHUNGCU" />
      <Association Name="KETCAUDUONG_DAT" Member="DATs" ThisKey="ID_KETCAUDUONG" OtherKey="ID_KETCAUDUONG" Type="DAT" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="ID_KH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="NGUOIDAIDIEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CHUCVU" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGUON" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="NGAYCAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOICAP" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MST" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="KHACHHANG_PHIEUYEUCAU" Member="PHIEUYEUCAUs" ThisKey="ID_KH" OtherKey="ID_KH" Type="PHIEUYEUCAU" />
    </Type>
  </Table>
  <Table Name="dbo.LOAICN" Member="LOAICNs">
    <Type Name="LOAICN">
      <Column Name="ID_LOAICN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAICN_THONGTINCONGTY" Member="THONGTINCONGTies" ThisKey="ID_LOAICN" OtherKey="ID_LOAICN" Type="THONGTINCONGTY" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIHINH" Member="LOAIHINHs">
    <Type Name="LOAIHINH">
      <Column Name="ID_LOAIHINH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAIHINH_BANGGIADAT" Member="BANGGIADATs" ThisKey="ID_LOAIHINH" OtherKey="ID_LOAIHINH" Type="BANGGIADAT" />
      <Association Name="LOAIHINH_VANPHONGCHOTHUE" Member="VANPHONGCHOTHUEs" ThisKey="ID_LOAIHINH" OtherKey="ID_LOAIHINH" Type="VANPHONGCHOTHUE" />
      <Association Name="LOAIHINH_CANHOCHUNGCU" Member="CANHOCHUNGCUs" ThisKey="ID_LOAIHINH" OtherKey="ID_LOAIHINH" Type="CANHOCHUNGCU" />
      <Association Name="LOAIHINH_CONGTRINHXAYDUNG" Member="CONGTRINHXAYDUNGs" ThisKey="ID_LOAIHINH" OtherKey="ID_LOAIHINH" Type="CONGTRINHXAYDUNG" />
      <Association Name="LOAIHINH_DAT" Member="DATs" ThisKey="ID_LOAIHINH" OtherKey="ID_LOAIHINH" Type="DAT" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIHOPDONG" Member="LOAIHOPDONGs">
    <Type Name="LOAIHOPDONG">
      <Column Name="ID_LOAIHOPDONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAIHOPDONG_HOPDONG" Member="HOPDONGs" ThisKey="ID_LOAIHOPDONG" OtherKey="ID_LOAIHOPDONG" Type="HOPDONG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAINHANVIEN" Member="LOAINHANVIENs">
    <Type Name="LOAINHANVIEN">
      <Column Name="ID_LOAINHANVIEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAINHANVIEN_NHANVIEN" Member="NHANVIENs" ThisKey="ID_LOAINHANVIEN" OtherKey="ID_LOAINHANVIEN" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.LOAITAISAN" Member="LOAITAISANs">
    <Type Name="LOAITAISAN">
      <Column Name="ID_LOAITAISAN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAITAISAN_CHITIETLOAI" Member="CHITIETLOAIs" ThisKey="ID_LOAITAISAN" OtherKey="ID_LOAITAISAN" Type="CHITIETLOAI" />
      <Association Name="LOAITAISAN_DACDIEMPHAPLY" Member="DACDIEMPHAPLies" ThisKey="ID_LOAITAISAN" OtherKey="ID_LOAITAISAN" Type="DACDIEMPHAPLY" />
      <Association Name="LOAITAISAN_LOAITHONGTIN" Member="LOAITHONGTINs" ThisKey="ID_LOAITAISAN" OtherKey="ID_LOAITAISAN" Type="LOAITHONGTIN" />
      <Association Name="LOAITAISAN_PHIEUYEUCAU" Member="PHIEUYEUCAUs" ThisKey="ID_LOAITAISAN" OtherKey="ID_LOAITAISAN" Type="PHIEUYEUCAU" />
    </Type>
  </Table>
  <Table Name="dbo.LOAITHONGTIN" Member="LOAITHONGTINs">
    <Type Name="LOAITHONGTIN">
      <Column Name="ID_LTT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_LOAITAISAN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LOAITHONGTIN_VANPHONGCHOTHUE" Member="VANPHONGCHOTHUEs" ThisKey="ID_LTT" OtherKey="ID_LTT" Type="VANPHONGCHOTHUE" />
      <Association Name="LOAITHONGTIN_CANHOCHUNGCU" Member="CANHOCHUNGCUs" ThisKey="ID_LTT" OtherKey="ID_LTT" Type="CANHOCHUNGCU" />
      <Association Name="LOAITHONGTIN_CONGTRINHXAYDUNG" Member="CONGTRINHXAYDUNGs" ThisKey="ID_LTT" OtherKey="ID_LTT" Type="CONGTRINHXAYDUNG" />
      <Association Name="LOAITHONGTIN_DAT" Member="DATs" ThisKey="ID_LTT" OtherKey="ID_LTT" Type="DAT" />
      <Association Name="LOAITAISAN_LOAITHONGTIN" Member="LOAITAISAN" ThisKey="ID_LOAITAISAN" OtherKey="ID_LOAITAISAN" Type="LOAITAISAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="ID_NHANVIEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="NGAYBATDAULAM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID_PHONGBAN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_LOAINHANVIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_PHANQUYEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[USER]" Member="USER" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PASS" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="ANH" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="NHANVIEN_HOPDONG" Member="HOPDONGs" ThisKey="ID_NHANVIEN" OtherKey="ID_NHANVIEN" Type="HOPDONG" />
      <Association Name="NHANVIEN_PHIEUYEUCAU" Member="PHIEUYEUCAUs" ThisKey="ID_NHANVIEN" OtherKey="ID_NHANVIEN" Type="PHIEUYEUCAU" />
      <Association Name="LOAINHANVIEN_NHANVIEN" Member="LOAINHANVIEN" ThisKey="ID_LOAINHANVIEN" OtherKey="ID_LOAINHANVIEN" Type="LOAINHANVIEN" IsForeignKey="true" />
      <Association Name="PHANQUYEN_NHANVIEN" Member="PHANQUYEN" ThisKey="ID_PHANQUYEN" OtherKey="ID_PHANQUYEN" Type="PHANQUYEN" IsForeignKey="true" />
      <Association Name="PHONGBAN_NHANVIEN" Member="PHONGBAN" ThisKey="ID_PHONGBAN" OtherKey="ID_PHONGBAN" Type="PHONGBAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="ID_PHANQUYEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PHANQUYEN_NHANVIEN" Member="NHANVIENs" ThisKey="ID_PHANQUYEN" OtherKey="ID_PHANQUYEN" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUYEUCAU" Member="PHIEUYEUCAUs">
    <Type Name="PHIEUYEUCAU">
      <Column Name="ID_PYC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_NHANVIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_LOAITAISAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_KH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOPYC" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="NGAYVIETPHIEU" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VITRI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DACDIEM" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MDTD" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TDTD" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="THHT" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="YEUCAUKHAC" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MUCPHICHAPTHUAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNGTRUOC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PHIEUYEUCAU_CHUNGTHUTDG" Member="CHUNGTHUTDGs" ThisKey="ID_PYC" OtherKey="ID_PYC" Type="CHUNGTHUTDG" />
      <Association Name="PHIEUYEUCAU_FILEDINHKEM" Member="FILEDINHKEMs" ThisKey="ID_PYC" OtherKey="ID_PYC" Type="FILEDINHKEM" />
      <Association Name="PHIEUYEUCAU_HOPDONG" Member="HOPDONGs" ThisKey="ID_PYC" OtherKey="ID_PYC" Type="HOPDONG" />
      <Association Name="KHACHHANG_PHIEUYEUCAU" Member="KHACHHANG" ThisKey="ID_KH" OtherKey="ID_KH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="LOAITAISAN_PHIEUYEUCAU" Member="LOAITAISAN" ThisKey="ID_LOAITAISAN" OtherKey="ID_LOAITAISAN" Type="LOAITAISAN" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUYEUCAU" Member="NHANVIEN" ThisKey="ID_NHANVIEN" OtherKey="ID_NHANVIEN" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGBAN" Member="PHONGBANs">
    <Type Name="PHONGBAN">
      <Column Name="ID_PHONGBAN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PHONGBAN_NHANVIEN" Member="NHANVIENs" ThisKey="ID_PHONGBAN" OtherKey="ID_PHONGBAN" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.QUANHUYEN" Member="QUANHUYENs">
    <Type Name="QUANHUYEN">
      <Column Name="ID_QUANHUYEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_TINHTHANH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="QUANHUYEN_BANGGIADAT" Member="BANGGIADATs" ThisKey="ID_QUANHUYEN" OtherKey="ID_QUANHUYEN" Type="BANGGIADAT" />
      <Association Name="QUANHUYEN_CANHOCHUNGCU" Member="CANHOCHUNGCUs" ThisKey="ID_QUANHUYEN" OtherKey="ID_QUANHUYEN" Type="CANHOCHUNGCU" />
      <Association Name="TINHTHANH_QUANHUYEN" Member="TINHTHANH" ThisKey="ID_TINHTHANH" OtherKey="ID_TINHTHANH" Type="TINHTHANH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINCONGTY" Member="THONGTINCONGTies">
    <Type Name="THONGTINCONGTY">
      <Column Name="TENCONGTY" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="TENTIENGANH" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VIETTAT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SDT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FAX" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QUOCGIA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="THANHPHO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GIAMDOC" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="KETOAN" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_LOAICN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="LOAICN_THONGTINCONGTY" Member="LOAICN" ThisKey="ID_LOAICN" OtherKey="ID_LOAICN" Type="LOAICN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TIENICHCHCC" Member="TIENICHCHCCs">
    <Type Name="TIENICHCHCC">
      <Column Name="ID_TIENICH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_CHCC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CANHOCHUNGCU_TIENICHCHCC" Member="CANHOCHUNGCU" ThisKey="ID_CHCC" OtherKey="ID_CHCC" Type="CANHOCHUNGCU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TINHTHANH" Member="TINHTHANHs">
    <Type Name="TINHTHANH">
      <Column Name="ID_TINHTHANH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TINHTHANH_QUANHUYEN" Member="QUANHUYENs" ThisKey="ID_TINHTHANH" OtherKey="ID_TINHTHANH" Type="QUANHUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.TRANGTHAI" Member="TRANGTHAIs">
    <Type Name="TRANGTHAI">
      <Column Name="ID_TRANGTHAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGUOITAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGUOISUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Member="TRANGTHAI1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TRANGTHAI_HOPDONG" Member="HOPDONGs" ThisKey="ID_TRANGTHAI" OtherKey="ID_TRANGTHAI" Type="HOPDONG" />
    </Type>
  </Table>
</Database>